### PR TITLE
Added arm64 to release architectures.

### PR DESCRIPTION
**Pull request by bart84ek**
This change is [Reviewable](https://reviewable.io/reviews/tooploox/oya/103)

### CODE REVIEW

**Review by magdalenasliwinska — APPROVED** [review]
Great job, keep it up!

**Review by bart84ek — COMMENTED** [review]
@magdalenasliwinska 

> *[Reviewable](https://reviewable.io/reviews/tooploox/oya/103#-:-NRDCEDi11EC60-3eJAl:b-m941jw)* status: 0 of 1 files reviewed, all discussions resolved

**Review by bart84ek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tooploox/oya/103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bart84ek)

**Review by magdalenasliwinska — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tooploox/oya/103#-:-NRDCnbF7trTF0KdIuDA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bart84ek)

**Review by magdalenasliwinska — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tooploox/oya/103)* status: all files reviewed, 1 unresolved discussion (waiting on @bart84ek)

___
*[`CHANGELOG.md` line 22 at r2](https://reviewable.io/reviews/tooploox/oya/103#-NWBhESl6egduoeMMchF:-NWBhESl6egduoeMMchG:bjo0i13) ([raw file](https://github.com/tooploox/oya/blob/f2e6909da263012ee8b954126266899cda01e88a/CHANGELOG.md#L22)):*
> ```Markdown
>        echo ${Oya[Import.Alias]}
>     ```
>     
> ```

Nit: trailing whitespace.
___
*[`.github/workflows/release.yml` line 13 at r2](https://reviewable.io/reviews/tooploox/oya/103#-NWBhUJg51hTUWyQ0LAK:-NWBhUJg51hTUWyQ0LAL:b-ruwkoq) ([raw file](https://github.com/tooploox/oya/blob/f2e6909da263012ee8b954126266899cda01e88a/.github/workflows/release.yml#L13)):*
> ```YAML
>     runs-on: macos-latest # ubuntu-latest
>     steps:
>       # - run: sudo apt-get update
> ```

Are these commands meant to be commented out?

**Pull request merged**
